sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
  skip_cleanup: true
  tag: latest
after_deploy:
  - npm run deploy



